### ISSUE TITLE
Class 'Brick\Geo\Engine\GeometryEngineRegistry' not found 

### ISSUE THREAD

**Issue by paskuale75** [brick/geo#11] opened 2017-09-10 10:31 UTC
Hi, I'm trying to use this repository but after creating a module and using it (with php 7.0):

`<?php
use Brick\Geo\Engine\GeometryEngineRegistry;
use Brick\Geo\Engine\PDOEngine;

class GisModule extends CWebModule
{

    public function init()
    {
        // this method is called when the module is being created
        // you may place code here to customize the module or the application

        // import the module-level models and components
        $pdo = new PDO('mysql:host=localhost', 'root', 'cecchino08');
        GeometryEngineRegistry::set(new PDOEngine($pdo));
    }
`

it return me this issue >> Class 'Brick\Geo\Engine\GeometryEngineRegistry' not found, the strange is that if I do ctrl + click the editor brings me to the class definition correctly.

**Comment by BenMorel** [comment] 2017-09-10 16:48
Hi, have you included the autoloader?

If you installed the library with Composer, you need to include this file from the root of your project:

    require 'vendor/autoload.php';

This autoloader works for all libraries installed with Composer, including brick/geo!

**Comment by paskuale75** [comment] 2017-09-11 08:38
thanks, try it now, I am developing with the php framework (Yii 1.x.x)

**Comment by paskuale75** [comment] 2017-09-11 08:43
great, now it works, thank you so much! Can I have a wiki to use this classes ?

**Comment by paskuale75** [comment] 2017-09-11 08:48
My error, I write in bad module :( after autoload.php import same issue

**Comment by paskuale75** [comment] 2017-09-11 08:50
$pdo connection points to a test database, maybe I have to run some migrating to define the tables?

**Comment by BenMorel** [comment] 2017-09-11 10:42
No, you do not need any database setup.
This is definitely an autoloading problem. Try the code below in isolation:

```php
<?php
require 'vendor/autoload.php';
$pdo = new PDO('mysql:host=localhost', 'root', 'cecchino08');
GeometryEngineRegistry::set(new PDOEngine($pdo));
```

It should not complain about a class not found.

**Comment by BenMorel** [comment] 2017-09-13 21:26
I'm closing this issue as it is an autoloader problem, and not a bug within the library itself.

**Closed by BenMorel** 2017-09-13 21:26 UTC
